#!/bin/bash

for f in $(find ~/.aliases.d/ -type f); do
    source $f
done

alias vi='nvim '

alias aliases='vi ~/.aliases'
alias envs='vi ~/.envs'

# From bash's help alias:
#
# A trailing space in VALUE causes the next word to be checked for alias
# substitution when the alias is expanded.
alias watch='watch --color '

alias ll='ls -Ghls --color=auto --group-directories-first --time-style=long-iso'

alias cp='cp -a'
alias rsync='rsync -a'

alias ccd='cd `xsel -b`'
alias cpwd='echo `pwd` | xsel -ib'

alias gp='git pull'

alias k='kubectl'
