#!/bin/bash

alias vi='nvim'

alias ll='ls -ls --group-directories-first'
alias pp='vim ~/vimwiki/passwords.wiki'

alias cp='cp -a'
alias rsync='rsync -a'

alias ccd='cd `xsel -b`'
alias cpwd='echo `pwd` | xsel -ib'

alias aliases='vi ~/.aliases'
alias envs='vi ~/.envs'
