#!/bin/bash

# fix mac LC_CTYPE issue
# see: http://sourabhbajaj.com/python/2014/03/31/fix-valueerror-unknown-locale-utf-8/
if [[ "$LC_CTYPE" == 'UTF-8' ]]; then
  export LC_CTYPE="en_US.UTF-8"
fi

install_dir=/usr/local/opt

#export TERMINAL=xfce4-terminal
export EDITOR=nvim
#export BROWSER=google-chrome

export PATH=$HOME/bin:/usr/local/bin:$PATH
export MANPATH="/usr/local/man:$MANPATH"

# go
export GOROOT=/usr/local/opt/go
export GOTMPDIR=$HOME/go/tmp
export GOCACHE=$HOME/go/cache
export GOPATH=$HOME/go
export GOBIN="$GOPATH/bin"
export GO111MODULE=auto

export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

prompt_git_current_branch() {
    local ref
    ref=$(command git symbolic-ref --quiet HEAD 2> /dev/null)
    local ret=$?
    if [[ $ret != 0 ]]; then
        [[ $ret == 128 ]] && return  # no git repo.
        ref=$(command git rev-parse --short HEAD 2> /dev/null) || return
    fi
    echo ${ref#refs/heads/}
}

prompt() {
    # Check https://github.com/sindresorhus/pure/blob/master/pure.zsh.
    # Fancy prompt symbol: ❯
    # Nice grey color: %F{242}

    local branch=$(prompt_git_current_branch)
    local kubectx=$(cat ~/.kube/config | grep 'current-context:' | cut -d ' ' -f 2)

    # Prompt turns red if the previous command didn't exit with 0.
    echo "\n%(?.%F{green}.%F{red})%~%f (%F{blue}$branch%f) (%F{blue}$kubectx%f)\n$ "
}

setopt PROMPT_SUBST
PROMPT='$(prompt)'
