#!/bin/bash

[[ "$TERM" == "xterm-kitty" ]] && alias ssh='TERM=xterm-256color ssh'

alias aliases='nvim ~/.aliases'
alias envs='nvim ~/.envs'

# From bash's help alias:
#
# A trailing space in VALUE causes the next word to be checked for alias
# substitution when the alias is expanded.
alias watch='watch --color '

alias agv='ag --ignore=vendor'
alias agvt="agv --ignore=vendor --ignore '*_test.go'"
alias brewup="brew update && brew upgrade && brew cleanup"
alias cp='cp -a'
alias cpwd='echo $(pwd) | pbcopy'
alias ct='docker run -it --rm -v $(pwd):/wd:ro --workdir=/wd --name ct quay.io/giantswarm/helm-chart-testing:v3.11.0 ct'
alias golint='golangci-lint run -E gosec -E goconst'
alias gp='git pull'
alias k='kubectl'
alias kg='kubectl --namespace giantswarm'
alias kc='kubectx'
alias kn='kubens'
alias klean="yq e 'del(.metadata.managedFields)' -"
alias kleaner="yq e 'del(.metadata.managedFields, .metadata.annotations.\"kubectl.kubernetes.io/last-applied-configuration\", .metadata.uid, .metadata.selfLink, .metadata.resourceVersion, .metadata.creationTimestamp)' -"
alias ll='ls -Ghls --color=auto --group-directories-first --time-style=long-iso'
alias ls='ls --group-directories-first --color=auto'
alias grep='grep --color=auto'
alias rsync='rsync -a'

alias gcloud-reset='docker container rm gcloud-config'
alias gcloud-init='docker run -ti --name gcloud-config gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine gcloud auth login'
# Check ~/.local/bin/gcloud
#alias gcloud=...
