#!/bin/bash

# Check not pushing to master/main branch.
branch=`git symbolic-ref HEAD`
if [ "$branch" = "refs/heads/master" ] || [ "$branch" = "refs/heads/main" ]; then
    if [[ $ALLOW_DIRECT_COMMIT_TO_MASTER -eq 1 ]]; then
        echo "ALLOW_DIRECT_COMMIT_TO_MASTER=1"
        echo "Allowing commit to master/main branch"
        exit 0
    fi

    echo "Direct commits to the branch master/main are not allowed"
    exit 1
fi

# Run gitleaks.
gitleaksEnabled=$(git config --bool hooks.gitleaks)
if [ "$gitleaksEnabled" = "true" ]; then
    gitleaks --verbose --redact --pretty
    if [ \$? -eq 1 ]; then
        echo >&2 "Error: gitleaks has detected sensitive information in your changes."
        echo >&2 "If you know what you are doing you can disable this check using:"
        echo >&2 "      git config hooks.gitleaks false"
        exit 1
    fi
fi
