#!/bin/bash

COMMIT_EDITMSG=$1

if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(master dev test)
fi

BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_NAME="${BRANCH_NAME##*/}"

BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")

# Take first part of the branch name split by '-'
a=($(echo $BRANCH_NAME | tr "-" " "))
ISSUE_NUM="${a[0]}"

# check if ISSUE_NUM is a number
re='^[0-9]+$'
if [[ $ISSUE_NUM =~ $re ]] ; then
  echo "[#$ISSUE_NUM] $(cat $COMMIT_EDITMSG)" >$COMMIT_EDITMSG
elif [[ $BRANCH_EXCLUDED -ne 1 ]]; then
  echo "prepare-commit-msg: Branch does not contain issue number: '$BRANCH_NAME'" 1>&2
  exit 1
fi
